---
baseURI: https://github.com/graphsense/graphsense-tagpacks/blob/master
targetKeyspace: tagpacks
fields:
  header:
    - title
    - creator
    - description
    - tags
  tag:
    - address
    - label
    - source
    - currency
    - category
    - lastmod
categories:
  - Organization
  - Miner
  - Exchange
  - Walletprovider
  - Marketplace
  - Mixingservice
  - Old/historic
  - Gambling
  - Services/others
  - Ransomware
  - Sextortion
  - Hack